name: Build and Deploy Index

on:
  workflow_dispatch:

  push:
    branches:
      - main

    paths:
      - 'catalog/**'

jobs:
  build-and-deploy-index:
    name: Get Changed Servers
    runs-on: ubuntu-latest

    outputs:
      servers: ${{ steps.set-servers.outputs.servers }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Build Index
        working-directory: scripts/index
        run: bun start

      - name: Publish Index
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mcp-containers-index
          directory: scripts/index/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
